[package]
name = "askama-bench"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[dependencies]
askama = { git = "https://github.com/djc/askama" }

[lib]
name = "askama_bench"
path = "askama.rs"
