[package]
name = "handlebars-bench"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[dependencies]
handlebars = { git = "https://github.com/sunng87/handlebars-rust" }
serde_json = "1"

[lib]
name = "handlebars_bench"
path = "handlebars.rs"
